# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        # will set the CC & CXX for cmake
        cc: gcc
        cxx: g++
        build-type: RelWithDebInfo
        # Extra options pass to cmake while configuring project
        configure-options: -DTESTS=ON
        run-test: true
        ctest-options: --test-dir test  --output-on-failure 
    - name: test-clang-format
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        exclude: './build ./FPGA/DFE ./FPGA/CPU/max ./util ./FPGA/CPU/inc'
        extensions: 'h,cpp'
        clangFormatVersion: 14
    - name: commit-clang-changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}