# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        # will set the CC & CXX for cmake
        cc: gcc
        cxx: g++
        build-type: RelWithDebInfo
        # Extra options pass to cmake while configuring project
        configure-options: -DTESTS=ON
        run-test: true
        ctest-options: --test-dir test  --output-on-failure 
    - uses: DoozyX/clang-format-lint-action@v0.11
    - name: test-clang-format
      with:
        source: '.'
        exclude: './build ./FPGA/DFE ./FPGA/CPU/max ./util'
        extensions: 'h,cpp'
        clangFormatVersion: 10
